config/routes.rb
FhsMeetIdeas::Application.routes.draw do
  # user authentication
  resource :user_sessions, :only => [:new, :create, :destroy]
  match "login" => "user_sessions#new"
  match "logout" => "user_sessions#destroy"

  # undo actions
  post "versions/:id/revert" => "versions#revert", :as => "revert_version"

  # projects
  resources :projects do
    resources :comments, :only => [:create]
    get :autocomplete_user_fullname, :on => :collection
  end

  #user
  resources :users, :only => [:index, :show]

  #followups
  resources :followups, :only => [:create, :destroy]

  #contact form
  get "contact" => "contact_form#new"
  post "contact" => "contact_form#create"

  # imprint page
  get "pages/imprint"

  # root route
  get "home/index"
  root :to => "Home#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_filter :require_login, :only => [:index]

  def index
    render current_user ? "user" : "guest"
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_intro.html.erb
<h1 id="intro"><%= image_tag "/images/headlines/meet-ideas.png" %> <%= t("home.intro").html_safe %></h1>

app/views/home/guest.html.erb
<% content_for :title, t("home.title") %>

<%= render "intro" %>

<div id="teaserBox">
  <div class="guest"><%= t("home.teaser") %></div>
  <a href="<%= url_for login_path %>" class="actionButton actionButtonGreen"><span><%= t("home.button_login") %></span></a>
</div>

app/views/home/user.html.erb
<% content_for :title, t("home.title") %>

<%= render "intro" %>

<div id="teaserBox">
  <div class="user"><%= t("home.teaser") %></div>
  <a href="<%= url_for projects_path %>" class="actionButton actionButtonGreen"><span><%= t(".projects") %></span></a>
  <a href="<%= url_for new_project_path %>" class="actionButton actionButtonBlue"><span><%= t(".new_project") %></span></a>
</div>