config/routes.rb
FhsMeetIdeas::Application.routes.draw do
  # user authentication
  resource :user_sessions, :only => [:new, :create, :destroy]
  match "login" => "user_sessions#new"
  match "logout" => "user_sessions#destroy"

  # undo actions
  post "versions/:id/revert" => "versions#revert", :as => "revert_version"

  # projects
  resources :projects do
    resources :comments, :only => [:create]
    get :autocomplete_user_fullname, :on => :collection
  end

  #user
  resources :users, :only => [:index, :show]

  #followups
  resources :followups, :only => [:create, :destroy]

  #contact form
  get "contact" => "contact_form#new"
  post "contact" => "contact_form#create"

  # imprint page
  get "pages/imprint"

  # root route
  get "home/index"
  root :to => "Home#index"
end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :description, :status, :title, :appointments_attributes, :pictures_attributes, :roles_attributes
  attr_searchable :created_at, :description, :status, :title, :updated_at

  has_paper_trail

  has_many :appointments, :dependent => :destroy
  has_many :comments, :dependent => :destroy
  has_many :pictures, :dependent => :destroy
  has_many :roles, :dependent => :destroy
  belongs_to :user

  has_many :followups, :dependent => :destroy
  has_many :users, :through => :followups

  accepts_nested_attributes_for :appointments, :reject_if => lambda { |a| a[:date].blank? || a[:description].blank? }, :allow_destroy => true
  accepts_nested_attributes_for :pictures, :reject_if => lambda { |a| a[:image].blank? || a[:title].blank? }, :allow_destroy => true
  accepts_nested_attributes_for :roles, :reject_if => lambda { |a| a[:title].blank? }, :allow_destroy => true

  validates_length_of :title, :within => 3..255, :too_short => I18n.t("validations.length.short", :attr => I18n.t("validations.attr.title"), :count => "%{count}"), :too_long => I18n.t("validations.length.long", :attr => I18n.t("validations.attr.title"), :count => "%{count}")
  validates :status, :presence => { :message => I18n.t("validations.attr.status") }
  validates_length_of :description, :within => 10..5000, :too_short => I18n.t("validations.length.short", :attr => I18n.t("validations.attr.description"), :count => "%{count}"), :too_long => I18n.t("validations.length.long", :attr => I18n.t("validations.attr.description"), :count => "%{count}")

  def self.remove_old
    Version.delete_all ["created_at < ?", 1.day.ago]
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  add_breadcrumb I18n.t("projects.index.title"), "/projects"

  autocomplete :user, :fullname, :full => true

  def index
    # thanks to railscast 251 (meta_search)
    @search_projects = Project.search(params[:search])
    @projects =  @search_projects.order("id DESC").paginate(:page => params[:page], :per_page => 10)
  end

  def show
    @project = Project.find(params[:id], :joins => :user, :select => "projects.*, users.email, users.fullname")
    @roles = @project.roles.select("name, title, user_id")
    @pictures = @project.pictures.select("image, title")
    @appointments = @project.appointments.select("date, description").order("date")
    @comments = @project.comments.paginate(:joins => :user, :page => params[:comments_page], :per_page => 5).select("comments.content, comments.created_at, comments.id, comments.user_id, users.email, users.fullname").order("comments.id")

    add_breadcrumb @project.title, @project
  end

  def new
    @project = Project.new
    @project.appointments.build
    @project.pictures.build
    @project.roles.build

    @statuses = PredefinedStatuses.order("status")
    @roles = PredefinedRoles.order("role")

    add_breadcrumb t("projects.new.title"), new_project_path
  end

  def create
    @project = Project.new(params[:project])
    @project.user_id = current_user.id

    if @project.save
      flash[:notice] = t("projects.new.saved") + " #{undo_link}"
      redirect_to @project
    else
      render "new"
    end
  end

  def edit
    @project = Project.find(params[:id])
    @statuses = PredefinedStatuses.order("status")
    @roles = PredefinedRoles.order("role")

    unless @project.user_id === current_user.id
      flash[:error] = t("projects.edit.denied")
      redirect_to @project
    end

    add_breadcrumb @project.title, @project
    add_breadcrumb t("common.edit"), edit_project_path(@project)
  end

  def update
    @project = Project.find(params[:id])
    @project.updated_at = Time.now

    if @project.update_attributes(params[:project])
      @project.followups.each do |follower|
        ProjectUpdateMailer.delay.project_update(User.find(follower.user_id), @project)
      end

      flash[:notice] = t("projects.edit.updated") + " #{undo_link}"
      redirect_to @project
    else
      render "edit"
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    flash[:notice] = t("projects.show.destroyed")
    redirect_to projects_path
  end

  private

  def undo_link
    view_context.link_to I18n.t("paper_trail.undo"), revert_version_path(@project.versions.scoped.last), :method => :post
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def allowed?
    @project.user_id === current_user.id
  end
end

app/views/projects/_appointments.html.erb
<div class="fields">
  <%= f.label :date, t("projects.form.date") %>
  <%- date_string = f.object.date && l(f.object.date) -%>
  <%= f.text_field :date, :class => "timepicker", :value => date_string %>
  <%= f.label :description, t("projects.form.appointment_description") %>
  <%= f.text_field :description %>
  <%= link_to_remove_fields t("projects.form.remove_appointment"), f %>
</div>

app/views/projects/_pictures.html.erb
<div class="fields">
  <%= f.label :image, t("projects.form.select_picture") %>
  <%= f.file_field :image %>
  <% if f.object.title.present? %>
    <%= f.object.title %>
    <%= image_tag f.object.image_url(:thumb), :alt => f.object.title %>
  <% else %>
    <%= f.label :title, t("projects.form.title") %>
    <%= f.text_field :title %>
  <% end %>
  <%= link_to_remove_fields t("projects.form.remove_picture"), f %><br />
</div>

app/views/projects/_projects.html.erb
<% content_for :javascript do %>
  <% if @project.errors.any? %>
    <script type="text/javascript">
      $(document).ready(function(){
        var noty_id = noty({
          "text":"<%= escape_javascript(@project.errors.full_messages.join("<br />")).html_safe %>",
          "layout":"topCenter",
          "type":"error",
          "timeout":10000
        });
      });
    </script>
  <% end %>
<% end %>

<%= form_for project, :html => { :multipart => true } do |f| %>
  <h2><%= t("projects.headlines.description") %></h2>
  <div>
    <%= f.label :title, t("projects.form.label_title") %><br />
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :status, t("projects.form.label_status") %><br />
    <%= f.select :status, @statuses.collect { |s| [ s.status, s.status ] } %>
  </div>
  <div>
    <%= f.label :description, t("projects.form.label_description") %><br />
    <%= f.text_area :description %>
  </div>
  <h2><%= t("projects.headlines.roles") %></h2>
  <div>
    <%= f.fields_for :roles do |builder| %>
      <%= render "roles", :f => builder %>
    <% end %>
    <p><%= link_to_add_fields t("projects.form.add_role"), f, :roles %></p>
  </div>
  <h2><%= t("projects.headlines.appointments") %></h2>
  <div>
    <%= f.fields_for :appointments do |builder| %>
      <%= render "appointments", :f => builder %>
    <% end %>
    <p><%= link_to_add_fields t("projects.form.add_appointment"), f, :appointments %></p>
  </div>
  <h2><%= t("projects.headlines.pictures") %></h2>
  <div>
    <%= f.fields_for :pictures do |builder| %>
      <%= render "pictures", :f => builder %>
    <% end %>
    <p><%= link_to_add_fields t("projects.form.add_picture"), f, :pictures %></p>
  </div>
  <div>
    <%= f.submit t("common.send") %>
  </div>
<% end %>

app/views/projects/_roles.html.erb
<div class="fields">
  <%= f.label :title, t("projects.form.role") %>
  <%= f.select :title, @roles.collect { |r| [ r.role, r.role ] }, {:include_blank => true } %>
  <%= f.label :name, t("projects.form.name") %>
  <%= f.autocomplete_field :name, autocomplete_user_fullname_projects_path, :update_elements => {:id => "#user_id_" + f.object_id.to_s} %>
  <%= f.hidden_field :user_id, :id => "user_id_" + f.object_id.to_s %>
  <%= link_to_remove_fields t("projects.form.remove_role"), f %>
</div>

app/views/projects/edit.html.erb
<% content_for :title, t(".title", :project => @project.title) %>
<% content_for :headline do %><%= image_tag "/images/headlines/edit.png" %> <%= t(".title", :project => @project.title) %><% end %>

<%= render "projects", :project => @project %>

<%= link_to t("common.back"), projects_path %>

app/views/projects/index.html.erb
<% content_for :title, t(".title") %>
<% content_for :headline do %><%= image_tag "/images/headlines/projects.png" %> <%= t(".title") %><% end %>

<p><%= link_to t(".new_project"), new_project_path %></p>

<%= form_for @search_projects do |f| %>
  <p>
    <%= f.label :title_or_description_contains, t("projects.form.label_search") %>
    <%= f.text_field :title_or_description_contains %>
    <%= f.submit t("common.search") %>
  </p>
  <%= f.sort_link :title, t("projects.index.sort_title") %> |
  <%= f.sort_link :status, t("projects.index.sort_status") %> |
  <%= f.sort_link :created_at, t("projects.index.sort_created") %> |
  <%= f.sort_link :updated_at, t("projects.index.sort_updated") %>
<% end %>

<ul id="projectlist">
  <% @projects.each do |project| %>
    <li>
      <div class="left">
        <%= link_to truncate(project.title, :length => 60), url_for(project) %><br />
        <p>
          <strong><%= t("projects.show.status") %></strong> <%= project.status %><br />
          <%= truncate(project.description, :length => 160) %>
        </p>
      </div>
      <% if following?(project.id) %>
        <%= link_to t("followups.links.unfollow"), followup_path(following?(project.id)), :method => :delete, :class => "followButton followButtonRed right" %>
      <% else %>
        <%= link_to t("followups.links.follow"), followups_path(:project_id => project), :method => :post, :class => "followButton followButtonGreen right" %>
      <% end %>
    </li>
    <div class="seperator"></div>
  <% end %>
</ul>

<%= will_paginate @projects, :renderer => PaginationListLinkRenderer %>
<div class="clear"></div>

app/views/projects/new.html.erb
<% content_for :title, t(".title") %>
<% content_for :headline do %><%= image_tag "/images/headlines/new.png" %> <%= t(".title") %><% end %>

<%= render "projects", :project => @project %>

<%= link_to t("common.back"), projects_path %>

app/views/projects/show.html.erb
<% content_for :title, @project.title %>
<% content_for :headline do %><%= image_tag "/images/headlines/info.png" %> <%= @project.title %><% end %>

<% if following?(@project.id) %>
  <p><%= link_to t("followups.links.unfollow"), followup_path(following?(@project.id)), :method => :delete, :class => "followButton followButtonRed right" %></p>
<% else %>
  <p><%= link_to t("followups.links.follow"), followups_path(:project_id => @project), :method => :post, :class => "followButton followButtonGreen right" %></p>
<% end %>

<h2><%= t("projects.headlines.description") %></h2>

<p>
  <strong><%= t(".published_by") %></strong> <%= @project.fullname %><br />
  <strong><%= t(".status") %></strong> <%= @project.status %>
</p>
<p><strong><%= t(".description") %></strong> <%= simple_format(h(@project.description)) %></p>

<% if @roles.count > 0 # ugly but necessary, because @roles.exists? does not work here %>
  <h2><%= t("projects.headlines.roles") %></h2>
  <ul id="roles" class="simpleListStyle">
    <% @roles.each do |role| %>
      <li><%= role.title %>:
      <% if role.name? %>
        <% if role.user_id %>
          <%= link_to role.name, user_path(role.user_id.to_i) %>
        <% else %>
          <%= role.name %>
        <% end %>
      <% else %>
          <strong><%= link_to t(".wanted"), project_path(@project, :anchor => "comments") %></strong>
      <%end %>
      </li>
    <% end %>
    <div class="clear"></div>
  </ul>
<% end %>

<% if @appointments.exists? %>
  <h2><%= t("projects.headlines.appointments") %></h2>
  <ul id="appointments" class="simpleListStyle">
    <% @appointments.each do |appointment| %>
      <li><%= l(appointment.date) %> - <%= appointment.description %></li>
    <% end %>
    <div class="clear"></div>
  </ul>
<% end %>

<% if @pictures.exists? %>
  <h2><%= t("projects.headlines.pictures") %></h2>
  <ul id="pictures">
    <% @pictures.each do |picture| %>
      <li>
        <span><%= picture.title %></span><br />
        <%= link_to image_tag(picture.image_url(:thumb), :alt => picture.title), picture.image_url, :class => "fancybox", :rel => "gallery1", :title => picture.title %>
      </li>
    <% end %>
    <div class="clear"></div>
  </ul>
<% end %>

<% if @project.followups.exists? %>
  <h2><%= t("projects.headlines.followups") %></h2>
  <ul id="followups" class="simpleListStyle">
    <% @project.followups.each do |followup| %>
      <li>
        <a href="<%= url_for(followup.user) %>">
          <%= followup.user.fullname %>
        </a>
      </li>
    <% end %>
    <div class="clear"></div>
  </ul>
<% end %>

<h2 id="comments"><%= t("projects.headlines.comments") %></h2>
<ul id="commentlist">
<% @comments.each do |comment| %>
  <li id="comment_<%= comment.id %>"><%= image_tag avatar_url(comment), :alt => t("common.gravatar") %> <div class="userinfo"><%= link_to comment.fullname, user_path(comment.user_id) %> <%= t(".timeText") %> <%= l(comment.created_at) %>:</div><br />
    <div class="content"><%= simple_format(h(comment.content)) %></div><br />
  </li>
<% end %>
</ul>
<%= will_paginate @comments, :param_name => "comments_page", :renderer => PaginationListLinkRenderer, :params => { :anchor => "comments" } %>
<div class="clear"></div>
<%= form_for [@project, @project.comments.build] do |f| %>
  <div id="commentForm">
    <%= f.label :content, t("projects.form.label_comment") %><br />
    <%= f.text_area :content, :rows => 3 %>
  </div>
  <div>
    <%= f.submit t("common.send") %>
  </div>
<% end %>

<h2><%= t(".contact") %></h2>

<%= mail_to @project.email, @project.email, :encode => "hex" %>

<p class="center small"><%= t(".last_modified", :last_modified => l(@project.updated_at)) %></p>

<p>
  <%= link_to t("common.back"), projects_path %>
  <% if allowed? %>
    | <%= link_to t("common.edit"), edit_project_path(@project) %>
    | <%= link_to t("common.delete"), project_path(@project), :method => :delete, :data => { :confirm => t(".deleteConfirmation") } %>
  <% end %>
</p>