config/routes.rb
FhsMeetIdeas::Application.routes.draw do
  # user authentication
  resource :user_sessions, :only => [:new, :create, :destroy]
  match "login" => "user_sessions#new"
  match "logout" => "user_sessions#destroy"

  # undo actions
  post "versions/:id/revert" => "versions#revert", :as => "revert_version"

  # projects
  resources :projects do
    resources :comments, :only => [:create]
    get :autocomplete_user_fullname, :on => :collection
  end

  #user
  resources :users, :only => [:index, :show]

  #followups
  resources :followups, :only => [:create, :destroy]

  #contact form
  get "contact" => "contact_form#new"
  post "contact" => "contact_form#create"

  # imprint page
  get "pages/imprint"

  # root route
  get "home/index"
  root :to => "Home#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="<%= t(".lang") %>">

<head>
  <meta charset="utf-8" />

  <title><%= yield :title %><%= t(".title_suffix") %></title>

  <meta name="description" lang="<%= t(".lang") %>" content="<%= t(".meta_description") %>" />
  <meta name="keywords" lang="<%= t(".lang") %>" content="<%= t(".meta_keywords") %>" />
  <meta name="robots" content="index, follow" />

  <%= stylesheet_link_tag "application" %>
  <%= stylesheet_link_tag "http://fonts.googleapis.com/css?family=Yanone+Kaffeesatz" %>
  <%= csrf_meta_tags %>
</head>

<body>
  <div id="outerWrapper">
    <div id="innerWrapper">
      <div id="logo">
        <a href="<%= url_for root_path %>"></a>
      </div>
      <div id="headerButtons">
        <% if(current_user) %>
          <div class="headerButton"><span><%= link_to t(".projects"), projects_path %> | <%= link_to t(".users"), users_path %></span></div>
          <div class="headerButton"><span><%= current_user.fullname %> | <%= link_to t(".logout"), logout_path %></span></div>
        <% else %>
          <a href="<%= url_for login_path %>" class="headerButton"><span><%= t(".login") %></span></a>
        <% end %>
      </div>
      <div class="clear"></div>
      <div id="content">
        <% if content_for?(:headline) %><h1><%= yield :headline %></h1><% end %>

        <% if @breadcrumbs %>
          <ul id="breadcrumbs">
            <li><%= t(".breadcrumbs") %> <%= link_to t(".homepage"), root_url %></li>
            <% @breadcrumbs.each do |txt, path| %>
              <li><%= link_to(h(txt), path) %></li>
            <% end %>
          </ul>
          <div class="clear"></div>
        <% end %>
        <%= yield %>
      </div>
    </div>
    <div id="footer">
      <div id="footerContent">
        <div id="fhsLogo"><%= link_to "", "http://www.fh-salzburg.ac.at/" %></div>
        <div id="footerText"><%= t(".footerText_1") %><br /><%= t(".footerText_2") %></div>
        <div id="footerLinks">
          <%= link_to t(".fhboerse"), "http://fhboerse.mediacube.at/" %> |
          <%= link_to t(".portfolio"), "http://portfolio.multimediatechnology.at/" %> |
          <%= link_to t(".contact"), contact_path %> |
          <%= link_to t(".imprint"), pages_imprint_path %></div>
      </div>
    </div>
  </div>
  <%= javascript_include_tag "application" %>
  <% if flash[:notice] || flash[:error] %>
  <script type="text/javascript">
    $(document).ready(function(){
      var noty_id = noty({
        "text":"<% if flash[:notice] %><%= escape_javascript(flash[:notice].html_safe) %><% else %><%= escape_javascript(flash[:error].html_safe) %><% end %>",
        "layout":"topCenter",
        "type":"<% if flash[:notice] %>success<% else %>error<% end %>",
        "timeout":10000
      });
    });
  </script>
  <% end %>
  <%= yield :javascript %>
</body>

</html>